### ISSUE TITLE
Example for running docker-paleocar

### ISSUE THREAD

**Issue by haohuuiuc** [openskope/docker-paleocar#1]
I pulled the openskope/paleocar image from dockerhub. I can see the syntax of usage which is "docker run openskope/paleocar Rscript <r-script-using-paleocar> [r-script-arguments]", is there an example of running the R script with parameters? Because I do not know how to locate the R script in the container.

**Comment by tmcphillips** [comment]
R scripts that run PaleoCAR are not provided in this container. As it is defined (see the very short Dockerfile), you can use this container to execute R scripts stored on the host system, and those R scripts can employ the paleocar package or any of its dependencies.  Thus if there is an R script `run_paleocar.R` in your current directory, you can run that script using the installation of R, gdal, paleocar, and paleocar's other dependencies installed in the container provided you mount the current host directory on the default working directory in the container (/workspace).

For example, on Windows:

    docker run -v %PWD%:/workspace openskope/paleocar run_paleocar.py

and on Linux or macOS:

    docker run -v $(pwd):/workspace openskope/paleocar run_paleocar.py

Similarly, you can start an interactive R session (with the paleocar package and its dependencies preinstalled) with the command:

    docker run -it openskope/paleocar R

If you want to build a docker container that includes scripts for automating a run of PaleoCAR you can build a new image using this one as its base, add the scripts to the image, and make sure the scripts are in the PATH variable of the skope user in the container.

**Comment by haohuuiuc** [comment]
Thanks! That definitely clarifies the issue.
